kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-project
    template:
      metadata:
        labels:
          app: my-project
      spec:
        containers:
          - name: my-project
            image: ankitpanchal040/my-project
            imagePullPolicy: Always
            ports:
              - containerPort: 80